In [6]:
from sqlalchemy import create_engine
import pandas as pd
from datetime import datetime 
import numpy as np

In [2]:
from config import db_password

In [11]:
listing_df = pd.read_csv("listing_info.csv")
listing_df

,date,zip,lat,lng,state,city,population,density,median_listing_price,median_days_on_market,median_listing_price_per_square_foot,median_square_feet,average_listing_price,total_listing_count
0,2020-07-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,320000.0,30,182.0,1800.0,399248.0,51.0
1,2020-08-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,280000.0,27,175.0,1600.0,368038.0,51.0
2,2020-09-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,297450.0,23,174.0,1680.0,367193.0,62.0
3,2020-10-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,305000.0,42,173.0,1736.0,370583.0,94.0
4,2020-11-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,302500.0,44,173.0,1740.0,391833.0,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
779551,2020-02-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,370000.0,30,171.0,1884.0,393681.0,49.0
779552,2020-03-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,380000.0,31,182.0,1915.0,424674.0,56.0
779553,2020-04-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,369000.0,32,180.0,1833.0,416689.0,60.0
779554,2020-05-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,389900.0,56,182.0,1944.0,431590.0,61.0
779555,2020-06-01,21286,39.41374,-76.57375,MD,Towson,19711.0,885.6,370000.0,25,186.0,1883.0,424208.0,65.0

In [12]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/Housing Market Analysis"

In [13]:
engine = create_engine(db_string)

In [15]:
listing_df.to_sql(name='housing', con=engine)

556